### ISSUE TITLE
The Link does not work

### ISSUE THREAD

**Issue by MrLeion** [microsoft/AI-For-Beginners#350]
https://microsoft.github.io/lessons/0-course-setup/setup

**Comment by leestott** [comment]
fixed with #344

**Comment by Chiemezuo** [comment]
I can confirm that this issue still happens when I try to open it on a new page.
However, on the same page, the issue does not happen.
